### ISSUE TITLE
Possible bug: region always active after opening an opml file

### ISSUE THREAD

**Issue by tonglianheng** [org-opml/org-opml#4]
If transient-mark-mode is on, opening a new OPML file will immediately make the whole buffer an active region.

**Comment by bsima** [comment]
Pretty sure this was fixed in commit 59662c16924dd56c42d5afe81f93964a5055da06 because the `opml-decode` function now properly returns the end-location `(point-max)` of the buffer. Previously, it would return the status code of `call-process-region` which would be 0 and thus move point to the beginning of the buffer.

So I'm closing this, but let me know if you still run into it.
