### ISSUE TITLE
Possible bug: OPML file content gets deleted if conversion to org failed

### ISSUE THREAD

**Issue by tonglianheng** [org-opml/org-opml#5]
When opening an OPML file, if the for some reason the conversion to org failed, e.g. opml2org.py cannot be found, then the OPML file gets overwritten by an empty file!

**Comment by tonglianheng** [comment]
I would say fixing this bug needs to be a priority.  I will be away for two weeks, so @bsima will you be able to have a look at this?  Otherwise I can do it when I am back.

**Comment by bsima** [comment]
@tonglianheng  Do you have an example opml file that causes the bug?

**Comment by tonglianheng** [comment]
Just one of the example files includedicated in the package. To reproduce, try remove the python script from search path, and open the file. Emacs would then complain an error executing org-opml. Then close emacs. Check the file again it should become empty.

-------- Original message --------

**Comment by bsima** [comment]
Ah, I see. I'll get to this asap

**Comment by bsima** [comment]
i think this is the issue: https://github.com/org-opml/org-opml/blob/master/org-opml.el#L46

i don't think it's necessary to erase the buffer...

**Comment by bsima** [comment]
okay well there seem to be only a few options for how to get around this:
1. Use better error handling. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Handling-Errors.html. Log errors to `*Messages*` instead of just failing and keep going
2. Instead of rewriting directly to the OPML buffer (as it currently does) use an intermediary buffer of some kind. This would require manual export from ORG -> OPML and I don't think that is ideal

I'm going with option 1 for now.
